import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/organisms/Footer";
import HeaderDektop from "@/app/components/organisms/desktop/HeaderDesktop";
import HeaderMobile from "@/app/components/organisms/mobile/HeaderMobile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <HeaderMobile />
          <HeaderDektop />
        </header>

        {children}
        <Footer />
      </body>
    </html>
  );
}
