import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@smastrom/react-rating/style.css";
import Footer from "@/app/_components/organisms/Footer";
import HeaderDektop from "@/app/_components/organisms/desktop/HeaderDesktop";
import HeaderMobile from "@/app/_components/organisms/mobile/HeaderMobile";
import AlertbarSection from "@/app/_components/organisms/AlertbarSection";
import { Analytics } from "@vercel/analytics/react";
import AuthSubscriber from "@/app/auth/AuthSubscriber";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <header className="sticky top-0 z-10">
          {/* <AuthSubscriber /> */}
          <HeaderDektop />
          <HeaderMobile />
        </header>
        <AlertbarSection />
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
