import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@smastrom/react-rating/style.css";
import Footer from "@/app/_components/organisms/Footer";
import HeaderDektop from "@/app/_components/organisms/desktop/HeaderDesktop";
import HeaderMobile from "@/app/_components/organisms/mobile/HeaderMobile";
import BackToTopSection from "@/app/_components/organisms/BackToTopSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <header>
          <HeaderMobile />
          <HeaderDektop />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
